---
title: "SCP Connectivity Analysis"
output: html_notebook
---

Sam Audrain August 2022
V 2.0
 
# Packages and functions
```{r}
library(dplyr)
library(ggplot2)

```

# Read in data
```{r}

###### CHANGE PATH FOR YOUR DATA #######
data<-read.csv("~/Dropbox/Sam/Schema_Consolidation_Project/R_SCP/SCP_StatsModels_GitHub/SCP_connectivity_data.csv")

```

# Correlation tests
```{r}
attach(data)

# a priori hypothesis testing: Do people with greater post-encoding anterior hippocampal-mPFC coupling have coarser congruent memories 3 days later?
cor.test(post_pre_AH_mPFC, coarse_related_long, alternative = "greater")

# exploratory correlations 
cor.test(post_pre_AH_mPFC, coarse_related_short, alternative = "two.sided")
cor.test(post_pre_AH_mPFC, fine_related_long, alternative = "two.sided")
cor.test(post_pre_AH_mPFC, coarse_unrelated_long, alternative = "two.sided")
cor.test(post_pre_AH_mPFC, fine_unrelated_long, alternative = "two.sided")

```

# Plot the a priori correlation 

Fig.3 of main manuscript
```{r, fig.height=6,fig.width=5.5}

data %>%
  ggplot(aes(y = coarse_related_long, x = post_pre_AH_mPFC)) +
  geom_smooth(method = lm, level = 0.95, color = "black") +
  geom_point(size = 5) +
  theme_classic() +
  theme(text = element_text(size = 18), axis.text.x = element_text(size=18), axis.text.y = element_text(size=18), plot.title = element_text(face="bold", hjust=0.5, size=22), legend.position="bottom")+
  scale_shape_manual(values=c(20))+
  guides(shape = FALSE, size = FALSE)+
  labs(y = "coarse congruent retrieval (% of congruent)",
       x = "ant. hipp - mPFC connectivity (post-pre)",
       title = "")

#ggsave(path = "~/Downloads/", width = 5.5, height = 6, device='tiff', filename = "fig3", dpi=500)

```
