---
title: "Supplemental Method 2: Proportion Forgotten"
output: html_notebook
---

Sam Audrain August 2022
V 2.0
 
Supplemental Analysis 2. Control analysis to check if PROPORTION of details forotten differs between congruent and incongruent. 

proportion forgotten = (short-long)/short

# Packages
```{r}
library(ggplot2)
library(nlme)
library(lme4)
library(emmeans)
library(lmerTest)
library(MuMIn)
library(Rmisc)

```

# Read in and subset the data
```{r}

###### CHANGE PATH FOR YOUR DATA #######
data<-read.csv("~/Dropbox/Sam/Schema_Consolidation_Project/R_SCP/SCP_StatsModels_GitHub/SCP_behavioural_data.csv")
data$CB_order<-as.factor(data$CB_order)

# subset the data
data_fine<-subset(data, granularity == "fine")
data_coarse<-subset(data, granularity == "coarse")

```


# Models 
```{r, fig.height=4.5,fig.width=4.5}
######## initital model fit #########
# model 
# model<-lmer(prop_forgetting ~ granularity*congruency + (1+CB_order|subj), data=data, na.action=na.omit)
# hist(residuals(model)) ## very skewed 
# plot(model)#very heteroskedastic 

### residuals not normal, severe negative skew
## I tried transforming the data with inverse, log, etc and just using weights and it didnt help
## skew is coming from some severe datapoints. 

######## final model fit #########
data_subset<-subset(data,include==1) ## have flagged 3 subjects with extreme datapoints in coarse congruent condition, a large increase in coarse congruent memory over time. Removing to deal with heteroskedasticity 

### corrected model, need to use lme so can add weights, because it's still a bit skewed and heteroskedastic even after removing most extreme outliers 
model<-lme(prop_forgetting ~ granularity*congruency, random= ~1+CB_order|subj, weights=varIdent(form=~1|granularity*congruency), data=data_subset, na.action=na.omit)

## re-check model assumptions 
hist(residuals(model)) #much better 
plot(model)#much better

#model stats 
anova(model)
intervals(model, level=0.95, which="fixed")
r.squaredGLMM(model)

# post hoc comparisons 
pairwise<-emmeans(model, list(pairwise ~ granularity*congruency), adjust = "none", lmer.df = "satterthwaite") 
pairwise
confint(pairwise, level=0.95, oldNames=FALSE, method="boot")

```

# Plot 
```{r, fig.height=4.5,fig.width=4.5}

# summarize 
stats<-summarySEwithin(data=data_subset, measurevar = "prop_forgetting", withinvars = c("granularity","congruency"), idvar = "subj", na.rm=TRUE)
# add se 
stats$upper_se<-stats$prop_forgetting + stats$se
stats$lower_se<-stats$prop_forgetting - stats$se
stats

# plot 
ggplot(stats, aes(x=congruency, y=prop_forgetting, fill=granularity)) +
  theme_classic() +
  geom_bar(stat = "identity", position = "dodge", width = 0.8, color = "black") +
  geom_errorbar(width = .0, position = position_dodge(0.8), aes(ymin=lower_se, ymax=upper_se))+
  geom_point(data=data_subset, position=position_jitterdodge(jitter.width=0.5, dodge.width = 0.8), pch=1, aes(congruency, prop_forgetting, group=granularity), show.legend = F, size = 2)+
  theme(axis.text=element_text(size=18), axis.title = element_text(size=20), axis.ticks.x=element_blank(), plot.title = element_text(size=22, face="bold", hjust=0.5), legend.text=element_text(size=16), legend.position = "bottom") +
  scale_fill_manual(values=c("#5D6D7E","#85929E","#D5D8DC"), labels = c("coarse", "detailed"))+
  scale_x_discrete(limits=c("R", "UR"), labels=c("R"="congruent", "UR"="incongruent"))+
  scale_y_continuous(breaks = seq(-3,1,0.5), expand = c(0, 0), limits = c(-3,1))+
  labs(x="", y="proportion forgotten", fill="")



```