---
title: "Supplementary Method 16: Post-encoding anterior hippocampus-mPFC connectivity correlation with coarse congruent memory plotted according to counterbalancing group"
output: html_notebook
---

Sam Audrain August 2022
V 2.0

# Packages 
```{r}
library(dplyr)
library(ggplot2)

```

# Read in data
```{r}

###### CHANGE PATH FOR YOUR DATA #######
data<-read.csv("~/Dropbox/Sam/Schema_Consolidation_Project/R_SCP/SCP_StatsModels_GitHub/SCP_connectivity_data.csv")

```

# Plot 
Supplementary Fig. 14
```{r, fig.height=6,fig.width=5.5}

data %>%
  ggplot(aes(y = coarse_related_long, x = post_pre_AH_mPFC, color = CB)) +
  geom_smooth(method = lm, level = 0.90, color = "black") +
  geom_point(size = 5) +
  theme_classic() +
  theme(text = element_text(size = 18), axis.text.x = element_text(size=18), axis.text.y = element_text(size=18), plot.title = element_text(face="bold", hjust=0.5, size=22), legend.position="bottom")+
  scale_color_manual(values=c("#2c7fb8","#253494"),labels=c("Group B","Group A"))+
  scale_shape_manual(values=c(20))+
  guides(shape = FALSE, size = FALSE)+
  labs(y = "coarse congruent recall (% of congruent)",
       x = "ant. hipp - mPFC connectivity (post-pre)",
       title = "")

```