---
title: "Supplementary Method 3: Congruency bias analysis"
output: html_notebook
---

Sam Audrain August 2022
V 2.0

# Read in Packages and Functions
```{r}

library(lme4)
library(ggplot2)
library(emmeans)
library(car)
library(lmerTest)
library(MuMIn)

source("summarySEwithin2.R")

```

# Read in the data 
```{r}

###### CHANGE PATH FOR YOUR DATA #######
data<-read.csv("~/Dropbox/Sam/Schema_Consolidation_Project/R_SCP/SCP_StatsModels_GitHub/R_congruency_bias.csv")

```


# Models

prop_bias = (lured by context-arbitraryFA)/total number of incorrect incongruent trials

```{r, fig.height=5,fig.width=4.5}

# model 
model<-lmer(prop_bias ~ delay + (1|subj), data=data, na.action=na.omit)

# check assumptions 
hist(residuals(model)) # should look normal 
#check for homogeneity of variance
#plot(model)#should look fairly uniform and random. It looks like there's a correlation but this is apparently ok: https://stats.stackexchange.com/questions/5235/what-is-the-expected-correlation-between-residual-and-the-dependent-variable? 
data2<-subset(data, !is.na(prop_bias)) #need to get rid of subjects that were dropped from the model/NA's, otherwise leveneTest will say mismatch
leveneTest(residuals(model) ~ data$delay) ## check for heteroskedasticity suggests ok 

# stats 
anova(model)
r.squaredGLMM(model)
confint(model, level=0.95, oldNames=FALSE, method="boot")
fixef(model)

# post hoc tests 
emmeans(model, list(pairwise ~ delay), adjust = "none", lmer.df = "satterthwaite") #pairwise comparisons 

# one sample t tests
data_short<-subset(data, delay=="short")
data_long<-subset(data, delay=="long")
t.test(data_short$prop_bias, mu = 0, alternative = "two.sided")
t.test(data_long$prop_bias, mu = 0, alternative = "two.sided")

```

Supplementary Fig. 3
```{r, fig.height=5,fig.width=4.5}

# prepare to plot 
## use estimated marginal means from the model 
eff_interaction <-emmeans(model, specs = c("delay")) #se is not for within subject data here
eff_interaction_df <- as.data.frame(eff_interaction)
## use within subject se 
stats<-summarySEwithin2(data=data, measurevar = "prop_bias", withinvars = c("delay"), idvar = "subj", na.rm=TRUE)
## add estiamted marginal mean to the stats dataset, and proper se 
stats$upper_se<-stats$prop_bias + stats$se
stats$lower_se<-stats$prop_bias - stats$se
stats

# plot 
ggplot(data, aes(x=delay, y=prop_bias)) + 
  theme_classic() +
  geom_boxplot(outlier.shape=NA) +
  geom_jitter(shape=16, position=position_jitter(0.2), size = 4) +
  theme(axis.text=element_text(size=18), axis.title = element_text(size=20), axis.ticks.x=element_blank()) +
  scale_y_continuous(breaks = seq(-0.5,1.1,0.1), limits = c(-0.5,1.1))+
  scale_x_discrete(limits=c("short", "long"), labels=c("short" = "short", "long" = "long"))+
  labs(x="", y="average congruency bias", fill="")
  
  
```

