---
title: "SCP Behavioural Analysis"
output: html_notebook
---

Sam Audrain August 2022
V 2.0
 
# Packages
```{r}

library(nlme)
library(ggplot2)
library(emmeans)
library(Rmisc)
library(lme4)
library(car)
library(lmerTest)
library(MuMIn)

```

# Read in and subset the data
```{r}

###### CHANGE PATH FOR YOUR DATA #######
data<-read.csv("~/Dropbox/Sam/Schema_Consolidation_Project/R_SCP/SCP_StatsModels_GitHub/SCP_behavioural_data.csv")
data$CB_order<-as.factor(data$CB_order)

# subset the data
data_fine<-subset(data, granularity == "fine")
data_coarse<-subset(data, granularity == "coarse")

```


# Total accuracy (collapsed across granularity)

```{r}
####### initital model fit ####### 
# model 
# model <-lmer(accuracy_rel ~ delay*congruency + (1+CB_order|subj), data=data, na.action=na.omit, control = lmerControl(optimizer ="Nelder_Mead"))
# 
# ## check model assumptions 
# hist(residuals(model)) #should be normally distributed 
# plot(model)#should look fairly uniform and random. There may be some slight heteroskedasticity here, so test formally with Levene's test
# data2<-subset(data, granularity == "coarse" & !is.na(accuracy_rel)) #need to get rid of subjects that were dropped from the model/NA's, otherwise leveneTest will say mismatch 
# leveneTest(residuals(model) ~ data2$congruency * data2$delay)
# leveneTest(residuals(model) ~ data2$congruency)
# leveneTest(residuals(model) ~ data2$delay)

###### final model fit ########
## since heteroskedastic, use varIdent and lme 
model<-lme(accuracy_rel ~ delay*congruency, random = ~1+CB_order|subj, data=data, na.action=na.omit, weights=varIdent(form=~1|congruency*delay))

# check heteroskedasticity
plot(model)

# model stats 
anova(model)
intervals(model, level=0.95, which="fixed")
r.squaredGLMM(model)

# post hoc tests 
pairwise<-emmeans(model, list(pairwise ~ delay:congruency), adjust = "none", lmer.df = "satterthwaite") 
pairwise
confint(pairwise, level=0.95, oldNames=FALSE, method="boot")

# descriptive stats
stats<-summarySEwithin(data=data, measurevar = "accuracy_rel", withinvars = c("delay","congruency"), idvar = "subj", na.rm=TRUE)
stats

```

# Coarse trial accuracy 

## Models 
```{r}
####### initital model fit ####### 
# model
# model<-lmer(accuracy_gran ~ delay*congruency+(1+CB_order|subj), data=data_coarse, na.action=na.omit, control = lmerControl(optimizer ="Nelder_Mead"))
# 
# #check model assumptions 
# hist(residuals(model)) ## should be normally distributed, it's looking skewed though
# plot(model)#should look fairly uniform and random
# shapiro.test(residuals(model)) #formally test normality of residuals, they are not normally distributed 

###### final model fit ########
# re-running the model transforming y variable to normalize by taking square root 
model<-lmer(sqrt(accuracy_gran) ~ delay*congruency+(1+CB_order|subj), data=data_coarse, na.action=na.omit, control = lmerControl(optimizer ="Nelder_Mead"))

# re-check new model assumptions 
hist(residuals(model)) ## should be normally distributed, looking good now 
plot(model)#should look fairly uniform and random, looking ok but test for heteroskedasticity 
shapiro.test(residuals(model)) #residuals are normal now 
## formally testing heteroskedasticity as well
data2<-subset(data, granularity == "coarse" & !is.na(accuracy_gran)) #need to get rid of subjects that were dropped from the model/NA's, otherwise leveneTest will say mismatch 
leveneTest(residuals(model) ~ data2$congruency * data2$delay)
leveneTest(residuals(model) ~ data2$congruency)
leveneTest(residuals(model) ~ data2$delay)
## looking good, can proceed 

# model stats 
anova(model)
confint(model, level=0.95, oldNames=FALSE, method="boot")
r.squaredGLMM(model)
fixef(model)

# post hoc tests 
pairwise<-emmeans(model, list(pairwise ~ delay:congruency), adjust = "none", lmer.df = "satterthwaite") 
confint(pairwise, level=0.95, oldNames=FALSE, method="boot")

# descriptive stats
stats<-summarySEwithin(data=data_coarse, measurevar = "accuracy_gran", withinvars = c("delay","congruency"), idvar = "subj", na.rm=TRUE)
stats

```

## Plot 

Figure 2 of manuscript. 
```{r, fig.height=4.5,fig.width=4.5}

# summarize the data 
stats2<-summarySEwithin(data=data_coarse, measurevar = "accuracy_gran", withinvars = c("delay","congruency"), idvar = "subj", na.rm=TRUE)
# add se 
stats2$upper_se<-stats2$accuracy_gran + stats2$se
stats2$lower_se<-stats2$accuracy_gran - stats2$se
stats2$gran<-rep("coarse", length(stats2$accuracy_gran))

# plot 
ggplot(stats2, aes(x=delay, y=accuracy_gran, fill=congruency)) +
  theme_classic() +
  geom_bar(stat = "identity", position = "dodge", width = 0.8, color = "black") +
  geom_errorbar(width = .0, position = position_dodge(0.8), aes(ymin=lower_se, ymax=upper_se))+
  geom_point(data=data_coarse, position=position_jitterdodge(jitter.width=0.5, dodge.width = 0.8), pch=1, aes(delay, accuracy_gran, group=congruency, fill=factor(congruency)), show.legend = F, size = 2)+
  theme(axis.text=element_text(size=18), axis.title = element_text(size=20), axis.ticks.x=element_blank(), plot.title = element_text(size=22, face="bold", hjust=0.5), legend.text=element_text(size=16), legend.position = "bottom") +
  scale_fill_manual(values=c("#85929E","#D5D8DC"), labels=c("congruent","incongruent"))+ ## manuscript 
  scale_x_discrete(limits=c("short", "long"), labels=c("short", "long"))+
  scale_y_continuous(breaks = seq(0,100,10),expand = c(0, 0), limits = c(0,100))+
  geom_hline(yintercept=0)+
  labs(x= "", y="% of total trials", fill="") +
  ggtitle("coarse")

#ggsave(path = "~/Downloads/", width = 4.5, height = 4.5, device='tiff', filename = "fig2", dpi=500)

```


# Detailed trial accuracy 

## Models 
```{r}
# model 
model<-lmer(accuracy_gran ~ delay*congruency + (1+CB_order|subj), data=data_fine, na.action=na.omit, control = lmerControl(optimizer ="Nelder_Mead"))

# check model assumptions 
hist(residuals(model))
plot(model)#should look fairly uniform and random. It does. 
shapiro.test(residuals(model)) #normal 

# model stats 
anova(model)
confint(model, level=0.95, oldNames=FALSE, method="boot")
fixef(model)
r.squaredGLMM(model)

# descriptive stats
stats<-summarySEwithin(data=data_fine, measurevar = "accuracy_gran", withinvars = c("delay","congruency"), idvar = "subj", na.rm=TRUE)
stats

```

## Plot 

Figure 2 of manuscript. 
```{r, fig.height=4.5,fig.width=4.5}

# summarize the data 
stats<-summarySEwithin(data=data_fine, measurevar = "accuracy_gran", withinvars = c("delay","congruency"), idvar = "subj", na.rm=TRUE)
# add se 
stats$upper_se<-stats$accuracy_gran + stats$se
stats$lower_se<-stats$accuracy_gran - stats$se
stats$gran<-rep("fine", length(stats$accuracy_gran))

# plot 
ggplot(stats, aes(x=delay, y=accuracy_gran, fill=congruency)) +
  theme_classic() +
  geom_bar(stat = "identity", position = "dodge", width = 0.8, color = "black") +
  geom_errorbar(width = .0, position = position_dodge(0.8), aes(ymin=lower_se, ymax=upper_se))+
  geom_point(data=data_fine, position=position_jitterdodge(jitter.width=0.25, dodge.width = 0.8), pch=1, aes(delay, accuracy_gran, group=congruency), show.legend = F, size = 2)+
  theme(axis.text=element_text(size=18), axis.title = element_text(size=20), axis.ticks.x=element_blank(), plot.title = element_text(size=22, face="bold", hjust=0.5), legend.text=element_text(size=16), legend.position = "bottom") +
  scale_fill_manual(values=c("#85929E","#D5D8DC"), labels=c("congruent","incongruent"))+ ## manuscript 
  scale_x_discrete(limits=c("short", "long"), labels=c("short", "long"))+
  scale_y_continuous(breaks = seq(0,100,10),expand = c(0, 0), limits = c(0,100))+
  geom_hline(yintercept=0)+
  labs(x= "", y="% of total trials", fill="") +
  ggtitle("detailed")

#ggsave(path = "~/Downloads/", width = 4.5, height = 4.5, device='tiff', filename = "fig2", dpi=500)

```






