---
title: "SCP Hippocampus RSA Modelling"
output: html_notebook
---

Sam Audrain November 2020 
V 0.0.1

# Packages
```{r}
library(nlme)
library(ggplot2)
library(emmeans)
library(psych)
library(Rmisc)

```


# Create datasets for stats comparisons
```{r}

# short = short delay data, long = long delay data
delays<-c("short", "long")

# R = congruent, UR = incongruent
conds<-c("R", "UR")

# ROIs
masks<-c("right_hippo_ant", "right_hippo_post")

# condition: same scene, similar scene, and cross context correlations
grans<-c("simscene", "samescene", "xcon")

# for memories remembered with fine granularity/detail only
grans2<-c("fine")

for (delay in delays){
  for (cond in conds){
    for (gran in grans){
      for(gran2 in grans2){
        for (mask in masks){
           data<-read.csv(paste("~/Dropbox/Sam/Schema_Consolidation_Project/R_SCP/SCP_StatsModels_GitHub/RSA_output/",cond,"_corrs_",gran,"_fine_",delay,"_",mask,".csv",sep=""),header = FALSE, sep=" ",stringsAsFactors = FALSE)
          colnames(data)<- c("subj", "trial", "mask", "R")
          data$R_fish<-fisherz(data$R)
          data$condition<-rep(gran, (nrow(data)))
          data$delay<-rep(delay, (nrow(data)))
          data$congruency<-rep(cond, (nrow(data)))
          # ensure consistent naming of counterbalanced subjects
          for (r in 1:nrow(data)){
            if (data[r,"subj"] == "P201_20181101"){
              data[r,"subj"]<-"P101_20181029"
            } else if (data[r,"subj"] == "S205_20181116"){
              data[r,"subj"]<-"S105_20181113"
            } else if (data[r,"subj"] == "S206_20181122"){
              data[r,"subj"]<-"S106_20181119"
            } else if (data[r,"subj"] == "S207_20181129"){
              data[r,"subj"]<-"S107_20181126"
            } else if (data[r,"subj"] == "S209_20190117"){
              data[r,"subj"]<-"S109_20190114"
            } else if (data[r,"subj"] == "S210_20190123"){
              data[r,"subj"]<-"S110_20190120"
            }
          }
          name<-paste(delay,mask,cond,gran,gran2,sep="_")
          assign(name,data) #saves the mean and std under the current masks name
        }
      }
    }
  }
}


#create ant hippo dataset 
hippo_right_ant_data_fine<-rbind(short_right_hippo_ant_R_simscene_fine,short_right_hippo_ant_R_samescene_fine,short_right_hippo_ant_R_xcon_fine, short_right_hippo_ant_UR_simscene_fine,short_right_hippo_ant_UR_samescene_fine,short_right_hippo_ant_UR_xcon_fine,long_right_hippo_ant_R_simscene_fine,long_right_hippo_ant_R_samescene_fine,long_right_hippo_ant_R_xcon_fine, long_right_hippo_ant_UR_simscene_fine,long_right_hippo_ant_UR_samescene_fine,long_right_hippo_ant_UR_xcon_fine)

# clean up enviro
rm(short_right_hippo_ant_R_simscene_fine,short_right_hippo_ant_R_samescene_fine,short_right_hippo_ant_R_xcon_fine, short_right_hippo_ant_UR_simscene_fine,short_right_hippo_ant_UR_samescene_fine,short_right_hippo_ant_UR_xcon_fine,long_right_hippo_ant_R_simscene_fine,long_right_hippo_ant_R_samescene_fine,long_right_hippo_ant_R_xcon_fine, long_right_hippo_ant_UR_simscene_fine,long_right_hippo_ant_UR_samescene_fine,long_right_hippo_ant_UR_xcon_fine)

#create post hippo dataset
hippo_right_post_data_fine<-rbind(short_right_hippo_post_R_simscene_fine,short_right_hippo_post_R_samescene_fine,short_right_hippo_post_R_xcon_fine, short_right_hippo_post_UR_simscene_fine,short_right_hippo_post_UR_samescene_fine,short_right_hippo_post_UR_xcon_fine,long_right_hippo_post_R_simscene_fine,long_right_hippo_post_R_samescene_fine,long_right_hippo_post_R_xcon_fine, long_right_hippo_post_UR_simscene_fine,long_right_hippo_post_UR_samescene_fine,long_right_hippo_post_UR_xcon_fine)

# clean up enviro
rm(short_right_hippo_post_R_simscene_fine,short_right_hippo_post_R_samescene_fine,short_right_hippo_post_R_xcon_fine, short_right_hippo_post_UR_simscene_fine,short_right_hippo_post_UR_samescene_fine,short_right_hippo_post_UR_xcon_fine,long_right_hippo_post_R_simscene_fine,long_right_hippo_post_R_samescene_fine,long_right_hippo_post_R_xcon_fine, long_right_hippo_post_UR_simscene_fine,long_right_hippo_post_UR_samescene_fine,long_right_hippo_post_UR_xcon_fine)

```

# Anterior hippocampus

## Short delay model
```{r}
# model
model<-lme(R_fish ~ condition*congruency, random= ~1|subj, data=hippo_right_ant_data_fine, na.action=na.omit, subset=delay=="short")
anova(model)

# prepare for plotting effect of condition on graph below
table1<-as.data.frame(emmeans(model, list(pairwise ~ condition), adjust = "none"))
table1<-subset(table1, contrast == ".")
table1$delay<-rep("short", (nrow(table1)))

```

## Long delay model 
```{r}
# model
model<-lme(R_fish ~ condition*congruency, random= ~1|subj, data=hippo_right_ant_data_fine, na.action=na.omit, subset=delay=="long")
anova(model)

#posthoc testing for main effect of cond
emmeans(model, list(pairwise ~ condition), adjust = "none") 

# prepare for plotting main effect of condition on graph below
table2<-as.data.frame(emmeans(model, list(pairwise ~ condition), adjust = "none"))
table2<-subset(table2, contrast == ".")
table2$delay<-rep("long", (nrow(table2)))
```

## Plot anterior hippocampus
```{r, fig.height=5,fig.width=4.5}
# plot of short and long delay on same plot, collapsed across congruency
# because there is no effect of congruency in the model 

eff_interaction<-rbind(table2,table1)
stats<-summarySEwithin(data=hippo_right_ant_data_fine, measurevar = "R_fish", withinvars = c("delay","condition"), idvar = "subj", na.rm=TRUE)
## add estiamted marginal mean to the stats dataset
stats$emmean<-eff_interaction$emmean
stats$upper_se<-stats$emmean + stats$se
stats$lower_se<-stats$emmean - stats$se
stats

ggplot(stats, aes(x=delay, y=emmean, fill=condition)) +
  theme_classic() +
  geom_bar(stat = "identity", position = "dodge", width = 0.8, color = "black") +
  geom_errorbar(width = .0, position = position_dodge(0.8), aes(ymin=lower_se, ymax=upper_se))+
  labs(x="", y="similarity (Fisher z)") +
  theme(axis.title = element_text(size=20), axis.ticks.x=element_blank()) +
  theme(axis.text=element_text(size=18))+
  labs(fill="") +
  scale_fill_manual(values=c("#5D6D7E","#85929E","#D5D8DC"), labels = c("same scene", "similar scene", "other context"))+
  scale_x_discrete(limits=c("short", "long"), labels=c("short", "long"))+
  scale_y_continuous(breaks = seq(0,0.08,0.01), expand = c(0, 0), limits = c(0,0.05))+
  geom_hline(yintercept=0)+
  ggtitle("anterior hippocampus")+
  theme(plot.title = element_text(size=22, face="bold", hjust=0.5), legend.text=element_text(size=16), legend.position = "bottom")

```

# Posterior hippocampus

## Short delay model
```{r}
# model
model<-lme(R_fish ~ condition*congruency, random= ~1|subj, data=hippo_right_post_data_fine, na.action=na.omit, subset=delay=="short")
anova(model)

#posthoc testing for main effect of cong
emmeans(model, list(pairwise ~ congruency), adjust = "none") 

# prepare for plotting effect of condition on graph below
table1<-as.data.frame(emmeans(model, list(pairwise ~ condition), adjust = "none"))
table1<-subset(table1, contrast == ".")
table1$delay<-rep("short", (nrow(table1)))

```

## Long delay model
```{r}
#### long delay 
model<-lme(R_fish ~ condition*congruency, random= ~1|subj, data=hippo_right_post_data_fine, na.action=na.omit, subset=delay=="long")
anova(model)

#posthoc testing for main effect of cond
emmeans(model, list(pairwise ~ condition), adjust = "none") 

# prepare for plotting main effect of condition on plot below
table2<-as.data.frame(emmeans(model, list(pairwise ~ condition), adjust = "none"))
table2<-subset(table2, contrast == ".")
table2$delay<-rep("long", (nrow(table2)))
```

## Plot posterior hippocampus
```{r, fig.height=5,fig.width=4.5}

eff_interaction<-rbind(table2,table1)
stats<-summarySEwithin(data=hippo_right_post_data_fine, measurevar = "R_fish", withinvars = c("delay","condition"), idvar = "subj", na.rm=TRUE)
## add estiamted marginal mean to the stats dataset
stats$emmean<-eff_interaction$emmean
stats$upper_se<-stats$emmean + stats$se
stats$lower_se<-stats$emmean - stats$se
stats

ggplot(stats, aes(x=delay, y=emmean, fill=condition)) +
  theme_classic() +
  geom_bar(stat = "identity", position = "dodge", width = 0.8, color = "black") +
  geom_errorbar(width = .0, position = position_dodge(0.8), aes(ymin=lower_se, ymax=upper_se))+
  labs(x="", y="similarity (Fisher z)") +
  theme(axis.title = element_text(size=20), axis.ticks.x=element_blank()) +
  theme(axis.text=element_text(size=18))+
  labs(fill="") +
  scale_fill_manual(values=c("#5D6D7E","#85929E","#D5D8DC"), labels = c("same scene", "similar scene", "other context"))+
  scale_x_discrete(limits=c("short", "long"), labels=c("short", "long"))+
  scale_y_continuous(breaks = seq(0,0.08,0.01), expand = c(0, 0), limits = c(0,0.05))+
  geom_hline(yintercept=0)+
  ggtitle("posterior hippocampus")+
  theme(plot.title = element_text(size=22, face="bold", hjust=0.5), legend.text=element_text(size=16), legend.position = "bottom")

```



